
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { Trip, Expense, Participant } from "@/types";
import { formatCurrency } from "./expenseCalculator";
import { format } from "date-fns";
import { getPaidByName } from "@/lib/utils";

// Helper function to create a simple PDF with basic styling
const createBasicPdf = () => {
  const pdf = new jsPDF("p", "pt", "a4");
  
  // Add company logo and name
  pdf.setFontSize(24);
  pdf.setTextColor(33, 150, 243); // Brand blue color
  pdf.text("Splittos", 40, 40);
  
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text("Expense Management Made Simple", 40, 55);
  
  pdf.setDrawColor(200, 200, 200);
  pdf.line(40, 65, 550, 65);
  
  return pdf;
};

// Function to calculate split amounts for an expense
const calculateSplitAmounts = (expense: Expense, participants: Participant[]) => {
  const splitDetails = [];
  
  // If custom split amounts are defined
  if (expense.splitAmounts) {
    for (const participantId of expense.splitBetween) {
      const participant = participants.find(p => p.id === participantId);
      if (participant) {
        splitDetails.push({
          name: participant.name,
          amount: expense.splitAmounts[participantId] || 0
        });
      }
    }
  } else {
    // Equal split
    const amount = expense.amount / expense.splitBetween.length;
    for (const participantId of expense.splitBetween) {
      const participant = participants.find(p => p.id === participantId);
      if (participant) {
        splitDetails.push({
          name: participant.name,
          amount
        });
      }
    }
  }
  
  return splitDetails;
};

// Function to generate a PDF report for an entire trip
export const generateTripPDF = async (trip: Trip): Promise<void> => {
  try {
    const pdf = createBasicPdf();
    
    // Add trip information header
    pdf.setFontSize(18);
    pdf.setTextColor(50, 50, 50);
    pdf.text(`Trip Report: ${trip.name}`, 40, 100);
    
    pdf.setFontSize(12);
    const dateRange = `${format(new Date(trip.startDate), "MMM d, yyyy")} - ${format(new Date(trip.endDate), "MMM d, yyyy")}`;
    pdf.text(dateRange, 40, 120);
    
    // Add participants
    pdf.setFontSize(14);
    pdf.text("Participants:", 40, 150);
    
    pdf.setFontSize(12);
    trip.participants.forEach((participant, index) => {
      pdf.text(`• ${participant.name} (Balance: ${formatCurrency(participant.balance, trip.currency)})`, 55, 170 + (index * 20));
    });
    
    // Add expenses summary
    const expenseY = 190 + (trip.participants.length * 20);
    pdf.setFontSize(14);
    pdf.text("Expenses Summary:", 40, expenseY);
    
    let totalExpenses = 0;
    trip.expenses.forEach(expense => totalExpenses += expense.amount);
    
    pdf.setFontSize(12);
    pdf.text(`Total Expenses: ${formatCurrency(totalExpenses, trip.currency)}`, 55, expenseY + 20);
    pdf.text(`Number of Expenses: ${trip.expenses.length}`, 55, expenseY + 40);
    
    // Add expense details
    pdf.setFontSize(14);
    pdf.text("Expense Details:", 40, expenseY + 70);
    
    let currentY = expenseY + 90;
    
    trip.expenses.forEach((expense, index) => {
      // Check if we need a new page
      if (currentY > 750) {
        pdf.addPage();
        currentY = 50;
      }
      
      const paidBy = typeof expense.paidBy === 'string'
        ? getPaidByName(expense.paidBy, trip.participants)
        : expense.paidBy.map(id => getPaidByName(id, trip.participants)).join(", ");
      
      pdf.setFontSize(12);
      pdf.setTextColor(33, 150, 243);
      pdf.text(`${index + 1}. ${expense.name} - ${formatCurrency(expense.amount, trip.currency)}`, 55, currentY);
      
      pdf.setTextColor(100, 100, 100);
      pdf.setFontSize(10);
      pdf.text(`Date: ${format(new Date(expense.date), "MMM d, yyyy")}`, 70, currentY + 15);
      pdf.text(`Category: ${expense.category}`, 70, currentY + 30);
      pdf.text(`Paid by: ${paidBy}`, 70, currentY + 45);
      
      if (expense.notes) {
        pdf.text(`Notes: ${expense.notes}`, 70, currentY + 60);
        currentY += 75;
      } else {
        currentY += 60;
      }
    });
    
    // Add footer
    pdf.setFontSize(10);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Generated by Splittos on ${format(new Date(), "MMM d, yyyy")}`, 40, 800);
    
    // Save the PDF
    pdf.save(`${trip.name}_Report.pdf`);
    
  } catch (error) {
    console.error("Error generating trip PDF:", error);
    throw error;
  }
};

// Function to generate a PDF for a single expense
export const generateExpensePDF = async (trip: Trip, expense: Expense): Promise<void> => {
  try {
    const pdf = createBasicPdf();
    
    // Add expense header
    pdf.setFontSize(18);
    pdf.setTextColor(50, 50, 50);
    pdf.text(`Expense Receipt: ${expense.name}`, 40, 100);
    
    // Add basic expense details
    pdf.setFontSize(14);
    pdf.text("Expense Details:", 40, 130);
    
    pdf.setFontSize(12);
    pdf.text(`Amount: ${formatCurrency(expense.amount, trip.currency)}`, 55, 150);
    pdf.text(`Date: ${format(new Date(expense.date), "MMM d, yyyy")}`, 55, 170);
    pdf.text(`Category: ${expense.category}`, 55, 190);
    
    // Add payer information
    const paidBy = typeof expense.paidBy === 'string'
      ? getPaidByName(expense.paidBy, trip.participants)
      : expense.paidBy.map(id => getPaidByName(id, trip.participants)).join(", ");
    
    pdf.text(`Paid by: ${paidBy}`, 55, 210);
    
    // Add split information
    pdf.setFontSize(14);
    pdf.text("Split Details:", 40, 240);
    
    // Calculate and show how the expense is split
    const splitDetails = calculateSplitAmounts(expense, trip.participants);
    
    pdf.setFontSize(12);
    let currentY = 260;
    splitDetails.forEach(split => {
      pdf.text(`• ${split.name}: ${formatCurrency(split.amount, trip.currency)}`, 55, currentY);
      currentY += 20;
    });
    
    // Add notes if available
    if (expense.notes) {
      pdf.setFontSize(14);
      pdf.text("Notes:", 40, currentY + 10);
      pdf.setFontSize(12);
      pdf.text(expense.notes, 55, currentY + 30);
      currentY += 50;
    }
    
    // Add trip reference
    pdf.setFontSize(14);
    pdf.text("Trip Reference:", 40, currentY + 10);
    pdf.setFontSize(12);
    pdf.text(`Trip: ${trip.name}`, 55, currentY + 30);
    const dateRange = `${format(new Date(trip.startDate), "MMM d, yyyy")} - ${format(new Date(trip.endDate), "MMM d, yyyy")}`;
    pdf.text(`Trip Dates: ${dateRange}`, 55, currentY + 50);
    
    // Add footer
    pdf.setFontSize(10);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Generated by Splittos on ${format(new Date(), "MMM d, yyyy")}`, 40, 800);
    
    // Save the PDF
    pdf.save(`${expense.name}_Receipt.pdf`);
    
  } catch (error) {
    console.error("Error generating expense PDF:", error);
    throw error;
  }
};

// Function to generate a detailed PDF for a group
export const generateGroupPDF = async (group: any): Promise<void> => {
  try {
    const pdf = createBasicPdf();
    
    // Add group information header
    pdf.setFontSize(18);
    pdf.setTextColor(50, 50, 50);
    pdf.text(`Group Report: ${group.name}`, 40, 100);
    
    pdf.setFontSize(12);
    pdf.text(`Created: ${format(new Date(group.createdAt), "MMM d, yyyy")}`, 40, 120);
    
    // Add participants
    pdf.setFontSize(14);
    pdf.text("Participants:", 40, 150);
    
    pdf.setFontSize(12);
    group.participants.forEach((participant: any, index: number) => {
      pdf.text(`• ${participant.name} (Balance: ${formatCurrency(participant.balance, group.currency || 'USD')})`, 55, 170 + (index * 20));
    });
    
    // Add expenses summary
    const expenseY = 190 + (group.participants.length * 20);
    pdf.setFontSize(14);
    pdf.text("Expenses Summary:", 40, expenseY);
    
    let totalExpenses = 0;
    group.expenses.forEach((expense: any) => totalExpenses += expense.amount);
    
    pdf.setFontSize(12);
    pdf.text(`Total Expenses: ${formatCurrency(totalExpenses, group.currency || 'USD')}`, 55, expenseY + 20);
    pdf.text(`Number of Expenses: ${group.expenses.length}`, 55, expenseY + 40);
    
    // Add expense details
    pdf.setFontSize(14);
    pdf.text("Expense Details:", 40, expenseY + 70);
    
    let currentY = expenseY + 90;
    
    group.expenses.forEach((expense: any, index: number) => {
      // Check if we need a new page
      if (currentY > 750) {
        pdf.addPage();
        currentY = 50;
      }
      
      const paidBy = typeof expense.paidBy === 'string'
        ? getPaidByName(expense.paidBy, group.participants)
        : expense.paidBy.map((id: string) => getPaidByName(id, group.participants)).join(", ");
      
      pdf.setFontSize(12);
      pdf.setTextColor(33, 150, 243);
      pdf.text(`${index + 1}. ${expense.name} - ${formatCurrency(expense.amount, group.currency || 'USD')}`, 55, currentY);
      
      pdf.setTextColor(100, 100, 100);
      pdf.setFontSize(10);
      pdf.text(`Date: ${format(new Date(expense.date), "MMM d, yyyy")}`, 70, currentY + 15);
      pdf.text(`Category: ${expense.category}`, 70, currentY + 30);
      pdf.text(`Paid by: ${paidBy}`, 70, currentY + 45);
      
      if (expense.notes) {
        pdf.text(`Notes: ${expense.notes}`, 70, currentY + 60);
        currentY += 75;
      } else {
        currentY += 60;
      }
    });
    
    // Add footer
    pdf.setFontSize(10);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Generated by Splittos on ${format(new Date(), "MMM d, yyyy")}`, 40, 800);
    
    // Save the PDF
    pdf.save(`${group.name}_Report.pdf`);
    
  } catch (error) {
    console.error("Error generating group PDF:", error);
    throw error;
  }
};
